In [1]:
# Example 3: NumPy - Boolean Indexing
import numpy as np
# Creating an array
array_1d = np.array([10, 20, 30, 40, 50])

# Boolean indexing
greater_than_30 = array_1d[array_1d > 30]

print('Elements Greater Than 20:', greater_than_30)

Elements Greater Than 20: [40 50]


In [1]:
# Example 18: NumPy - Meshgrid Creation
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Create the meshgrid
X, Y = np.meshgrid(x, y)

print("X Grid:")
print(X)

print("\nY Grid:")
print(Y)

X Grid:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

Y Grid:
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [1]:
# Example 17: NumPy - Linear Space Array
import numpy as np

# Generating a linear space array
linear_space = np.linspace(0, 20, 10)
print("Linear Space Array:", linear_space)


Linear Space Array: [ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [1]:
# Example 9: NumPy - Multi-dimensional Slicing
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[10, 11, 12], [13, 14, 15]],
                     [[19, 20, 21], [22, 23, 24] ]])



sliced_array = array_3d[0:2, 1:3, 0:2]

print("\nSliced 3D Array :")
print(sliced_array)


Sliced 3D Array :
[[[ 4  5]]

 [[13 14]]]
